from data.data import Datos
import custom_exceptions

class DatosValor(Datos):
    pass